<?php
$string="rakib";
switch($string)
{
    case"sakib":
        echo"sakib";
        echo"</br>";
        break;
    case"rakib":
        echo"rakib";
        echo"</br>";
        break;
    case"aman":
        echo"aman";
        echo"</br>";
        break;
    default:
    echo"rakib is absent";
}
?>